name: "Check step"
description: "Initial checks"
inputs:
  step:
    description: "What step"
  skip_branch_check:
    description: "Skip branch check"
    required: false
    default: false

runs:
  using: composite
  steps:
    - id: get_step
      shell: bash
      run: echo "step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT

    - name: Debug output
      shell: bash
      run: |
        echo "${{ steps.get_step.outputs.step }}"
        echo "${{ toJSON(github) }}"

    - name: Check if correct step
      if: ${{ steps.get_step.outputs.step != inputs.step }}
      shell: bash
      run: exit 1

    - name: Check if template repository
      if:  github.event.repository.is_template
      shell: bash
      run: exit 1

    - name: Check if branch isn't correct
      if: ${{ !inputs.skip_branch_check && github.ref_type == 'branch' && github.ref_name != format('lesson/{0}', inputs.step) }}
      shell: bash
      run: exit 1