name: Step 3, Open a pull request

# This step listens for the learner to open a pull request with branch `my-first-branch`.
# This workflow updates from step 3 to step 4.

# This will run every time we create a branch or tag.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened

# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write


jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  check_conditions:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      # Needed so we can read the step number from -step.txt
      - name: Checkout
        uses: actions/checkout@v4

      - id: get_step
        run: echo "step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT

      - name: Check if correct step
        if: ${{ steps.get_step.outputs.step != 3 }}
        run: exit 1

      - name: Check if template repository
        if:  github.event.repository.is_template
        run: exit 1

      - name: Check if branch is my-first-branch
        if: github.head_ref != 'my-first-branch'
        run: exit 1

  main:
    needs: check_conditions
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || success()
    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches.
          ref: my-first-branch # Important, as normally `pull_request` event won't grab other branches.

      # In README.md, switch step 3 for step 4.
      - name: Update to step 4
        uses: action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 3
          to_step: 4
          branch_name: my-first-branch
