name: Step 3

on:
  workflow_dispatch:
  create:

# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  check_conditions:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      # Needed so we can read the step number from -step.txt
      - name: Checkout
        uses: actions/checkout@v4

      - id: get_step
        run: echo "step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT

      - name: Debug
        run: echo "${{ steps.get_step.outputs.step }}"

      - name: Debug
        run: echo "${{ toJSON(github) }}"


      - name: Check if correct step
        if: ${{ steps.get_step.outputs.step != 3 }}
        run: exit 1

      - name: Check if template repository
        if:  github.event.repository.is_template
        run: exit 1

      - name: Check if branch is lesson/3
        if: github.ref_type == 'branch' && github.ref_name != 'lesson/3'
        run: exit 1

  main:
    needs: check_conditions
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || success()
    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches.

      # In README.md, switch step 3 for step 4
      - name: Update to step 4
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 3
          to_step: 4
          branch_name: lesson/3
